import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import contactRoutes from './contactRoutes.js';
import donationRoutes from './donationRoutes.js';
import allocationRoutes from './allocationRoutes.js';
import volunteerRoutes from './volunteerRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import programRoutes from './programRoutes.js';
import kpiRoutes from './kpiRoutes.js';
import staffRoutes from './staffRoutes.js';
import feePlanRoutes from './feePlanRoutes.js';
import feeRoutes from './feeRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import waiverRoutes from './waiverRoutes.js';
import subsidyRoutes from './subsidyRoutes.js';
import vendorRoutes from './vendorRoutes.js';
import requisitionRoutes from './requisitionRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import healthRoutes from './healthRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/contacts', contactRoutes);
router.use('/donations', donationRoutes);
router.use('/allocations', allocationRoutes);
router.use('/volunteers', volunteerRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/programs', programRoutes);
router.use('/kpis', kpiRoutes);
router.use('/staff', staffRoutes);
router.use('/fee-plans', feePlanRoutes);
router.use('/fees', feeRoutes);
router.use('/payments', paymentRoutes);
router.use('/waivers', waiverRoutes);
router.use('/subsidies', subsidyRoutes);
router.use('/vendors', vendorRoutes);
router.use('/requisitions', requisitionRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/', healthRoutes);

export default router;
